//CSE PROJECT GROUP 9.
//Parashar 
//Ankith
//Manoj
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
void guess3(int N)//In or out game
{
	int num1,num2,num3,guess,points=100,amt=0,opt;
	printf("\t\t\t\t\t---------------------------------------\n");
	printf("\t\t\t\t\t|             IN OR OUT!!             |\n");
   	printf("\t\t\t\t\t---------------------------------------\n\n");
	printf("\t\t\t\t\tYou are awarded with 100 bet credits!!\a\n\n");
	printf("Rules are simple :\n");
	printf("\t1.Press Y if you want to bet or else Press N.\n");
	printf("\t2.By pressing N you are not going to bet so your bet credits wont be affected. \a\n\n");
	printf("-------------------------------------------------------------------------\n");
	printf("| NOTE : ALL 3 NUMBERS GENERATED BY THE MACHINE ARE IN THE RANGE 0 - 40.|\n");
	printf("-------------------------------------------------------------------------\n");
	while(1)
	{
	  	srand(time(NULL));
	  	num1 = rand() % 40;//generate random number 1 
   		num2 = rand() % 40;//generate random number 2 
   		num3 = rand() % 40;//generate random number 3
    	if(num1>num2)
    	{
    		int temp;
    		temp=num1;
    		num1=num2;
       		num2=temp;
		}//interchanging the numbers and making num1 > num2
		printf("Generating random number ...\n");
	 	while(num1==num2 || num2==num1+1)
      	{
         	if(num2 == num1+1|| num2 == num1+2 || num1==num2) num2 = rand() % 40;
      	}//
	   	printf("-----------------------------------------------------------\n");
	   	printf("1st Number is %d\n2nd Number is %d\n\a",num1,num2);
	  	char c;
	  	fflush(stdin);
	  	printf("Press Y to bet N to skip and E to exit:");
	   	scanf("%c",&c);
	   	printf("Bet Credits = %d\n",points);
	   	if(c==89 || c==121)    
	   	{
	   		here:
		   	printf("Enter Bet amount : ");
		   	scanf("%d",&amt);
		   	if(amt>points)
		   	{
		   		printf("Bet Amount entered is exceeding the amount exsisting with you\nMaximum amount you can bet right now = Rs.%d\n\n",points);
		   		goto here;
			}
		   	printf("Loading ...\n");
		   	printf("Will the third number lie in between the Numbers shown above ?\n");
		   	printf("If you think the numbers lie in between Number 1 and Number 2\nChoose option 1 \n");
		   	printf("If you think the numbers does not lie in between Number 1 and Number 2\nChoose option 2 \n");
		   	star:
		   	printf("Options:\n|1|.Middle\n|2|.Not in middle \n");
		   	scanf("%d",&opt);
		   	if(opt == 1)
		   	{
			
		   		if(num3>num1 && num3<num2)
		   		{
		    		points=points+amt;
					printf("You win !\nAnd the 3rd number is %d\nPoints = %d\n",num3,points);
					printf("-----------------------------------------------------------\n");	
		 		}
				else
				{
		  			points=points-amt;
		  			printf("Wrong answer\nThird Number is %d\nRemaining Points = %d\n",num3,points);
		  			printf("-----------------------------------------------------------\n");
	    		}
	    	}
	    	else if(opt == 2)
	    	{
	    		if(num3>num1 && num3<num2)
		   		{
		   			points=points-amt;
		  			printf("Wrong answer\nThird Number is %d\nRemaining Points = %d\n",num3,points);
		  			printf("-----------------------------------------------------------\n");
		    			
		 		}
		 		else
				{
		  			points=points+amt;
					printf("You win !\nAnd the 3rd number is %d\nPoints = %d\n",num3,points);
					printf("-----------------------------------------------------------\n");
	    		}
			}
			else
			{
				printf("Please Choose either 1 or 2");
				goto star;
			}
		}
        	else if(c==78 || c==110)
	   		{
	       		printf("3rd Number is %d\n",num3);
	       		printf("-----------------------------------------------------------\n");
	    	}
	    	else if(c==69 || c==101) break;
	    	else
	    	{
	   			printf("Terminated !!\n");
	   	  		printf("-----------------------------------------------------------\n");
			}
			if(points<0 || points==0) break;
    }

}
void guess2(int N)
{
	int num,num2, guess, numberofguess = 0,points=100,play,amt;
	printf("\t\t\t\t\t---------------------------------------\n");
    printf("\t\t\t\t\t|            Guess What!!!            |\n");
	printf("\t\t\t\t\t---------------------------------------\n\n");
	printf("\t\t\t\t\t\tCongratulations !!\n\t\t\t\t\tYou are awarded with 100 Points!!\n\n");
	printf("\t\t\t\t\t\tRules are simple :\n\n");
	printf("1.Machine develops 2 numbers and in between 0 and 40 they wont be shown to you\n\n");
	printf("2.All you have to do is guess those two numbers and predict a third number\n\n");
	printf("3.If the third number you guessed is in between the two numbers generated by machine you win or else you lose\n\n");
	printf("**NOTE 1 : (-)BET AMOUNT FOR EVERY WRONG GUESS\n\n");
	printf("**NOTE 2 : Only enter numbers\n\n");
	printf("**NOTE 3 : Entering a number greater than 40 exits the game, So please play carefully and enter a number greater than 40 to exit\n\n");
	// Generate a random number
	start:
	printf("-----------------------------------------------------------\n");
	if(points>0)
 	{
	  	srand(time(NULL));
	  	num = rand() % 40;
      	num2 = rand() % 40;
      	while(num==num2 || num==num2+1)
      	{
         	if(num == num+1|| num == num+2 || num==num) num2 = rand() % 40;
      	}
      		if(num>num2)
    	{
    		int temp;
    		temp=num;
    		num=num2;
    		num2=temp;
	    }//interchanging the numbers and making num1 > num2
      	printf("Hint : There are %d numbers in between number 1 and number 2\n\n",num2-num-1); 
	  	printf("Enter a number between 0 and 40 : ");
      	scanf("%d",&guess);
      	amount:
      	printf("Enter bet amount = ");
      	scanf("%d",&amt);
      	if(amt<=points)
      	{
        	if(guess>=num && guess<=num2)
      		{
	    		points=points+amt;
	    		printf("YOU WON!!\nPoints = %d\n\a\a",points);
				printf("The numbers are %d,%d\n\n",num,num2);	
	    		goto start;
	  		}
	  		else if(guess>40)
	  		goto terminate;
	  		else
	  		{
	  			points=points-amt;
	  			printf("You lost this time play carefully\n\a\a");
	  			printf("Points = %d\n",points);
	  			printf("The numbers are %d,%d\n",num,num2);
	  			goto start;
	  		}
		}
		else
		{
			printf("Bet Amount entered is exceeding the amount exsisting with you\nMaximum amount you can bet right now = Rs.%d\n\n",points);
			goto amount;
		}
	}
    else
    printf("You Used all your points \nEnter again to win rewards\n");
    terminate:
    printf("-----------------------------------------------------------\n");
}

void guess(int N)
{
	int number, guess, numberofguess = 1;
	srand(time(NULL));
	number = rand() % 100;
	printf("\t\t\t\t\t---------------------------------------\n");
    printf("\t\t\t\t\t|       Welcome to Hi-Lo game         |\n");
    printf("\t\t\t\t\t---------------------------------------\n\n");
    printf("\t\t\t\t\t\tRules are simple :\n\n");
    printf("%c Hi! is printed if the number entered by user is less than the number generated by compiler , then user needs to enter a bigger number than before .\n\n",21);
    printf("%c Lo! is printed if the number entered by user is higher than the number generated by compiler , then user needs to enter a smaller number than before .\n\n",21);
    printf("\t\t\t     --------------------------------------------------------------\n");
	printf("\t\t\t     |  Guess a number between 1 and %d, you only have 10 tries! |\n",N);
	printf("\t\t\t     --------------------------------------------------------------\n");
	printf("\t\t\t                                  |\n\t\t\t                                  |\n\t\t\t                                  |\n\t\t\t                                  V\n");
	do 
	{

			if (numberofguess > 10) 
			{
				printf("\nYou Lose!\n");
				printf("The number is %d",number);
				break;
			}
			scanf("%d", &guess);
			if (guess > number)

			{
				printf("|------> Lo!\n");
				numberofguess++;
			}
			else if (number > guess)
			{
				printf("|------> Hi!\n");
				numberofguess++;
			}
			else
			printf("Partyyy time !! %c\nYou guessed the number in %d attempts!\n",2,numberofguess);

	}while (guess != number);
	printf("\t\t\t\t\t\t\t%c%c%c\n",2,2,2);
	
}
int main()
{
	printf("\t\t\t---------------------------------------------------------------------------------------------------------------------------------------------------------------\n"
"\t\t\t |||||||||||||| |||||||||||||| ||||||          |||||| ||||||||||||||    ||||||          |||||| |||||||||||||| ||||||||||||||||   ||||||         ||||||||||||   \n"
"\t\t\t |||||||||||||| |||||||||||||| |||||||||||||||||||||| ||||||||||||||    ||||||          |||||| |||||||||||||| ||||||||||||||||   ||||||         |||||||||||||| \n"
"\t\t\t |||||||||||||| |||||||||||||| |||||||||||||||||||||| ||||||||||||||    ||||||          |||||| |||||||||||||| ||||||||||||||||   ||||||         |||||||||||||| \n"
"\t\t\t ||||||         ||||||  |||||| |||||||||||||||||||||| ||||||            ||||||          |||||| ||||||  |||||| ||||||    ||||||   ||||||         ||||||  |||||| \n"
"\t\t\t ||||||         |||||||||||||| ||||||  ||||||  |||||| ||||||||||||||    ||||||  ||||||  |||||| ||||||  |||||| ||||||||||||||||   ||||||         ||||||  |||||| \n"
"\t\t\t ||||||  |||||| |||||||||||||| ||||||  ||||||  |||||| ||||||||||||||    ||||||  ||||||  |||||| ||||||  |||||| ||||||||||||||||   ||||||         ||||||  |||||| \n"
"\t\t\t ||||||  |||||| |||||||||||||| ||||||  ||||||  |||||| ||||||||||||||    ||||||  ||||||  |||||| ||||||  |||||| ||||||||||||||||   ||||||         ||||||  |||||| \n"
"\t\t\t ||||||  |||||| ||||||  |||||| ||||||          |||||| ||||||            |||||||||||||||||||||| ||||||  |||||| ||||||  ||||||     ||||||         ||||||  |||||| \n"
"\t\t\t |||||||||||||| ||||||  |||||| ||||||          |||||| ||||||||||||||    |||||||||||||||||||||| |||||||||||||| ||||||  |||||||||| |||||||||||||| |||||||||||||| \n"
"\t\t\t |||||||||||||| ||||||  |||||| ||||||          |||||| ||||||||||||||    |||||||||||||||||||||| |||||||||||||| ||||||  |||||||||| |||||||||||||| |||||||||||||| \n"
"\t\t\t |||||||||||||| ||||||  |||||| ||||||          |||||| ||||||||||||||    ||||||  ||||||  |||||| |||||||||||||| ||||||  |||||||||| |||||||||||||| ||||||||||||   \n"
"\t\t\t------------------------------------------------------------------------------------------------------------------------------------------------------------\n");
	int num,N = 100,z,fee=100,n,check;
	char x;
	{
		start:
		srand(time(NULL));
		num=rand()%100000;
		printf("\t\t\tEntry Fee = Rs.100/-\n\n");
		printf("\t\t\tPay the entry fee here : ");
		scanf("%d",&n);
		if(n>=fee)
		{
			printf("\n\t\t\tEntry confirmed!\n");
			printf("\t\t\tCollect your change here :Rs.%d\n",n-fee);
			printf("\t\t\tYour Entry code is: %d\n\n",num);	
		}
		else if(n<fee)
		{
			printf("\tSorry! Please pay the complete fee to enter.\n\tYour amount is refunded\n\n"); goto start;
		}
		check:
		printf("Enter your entry code :");
		scanf("%d",&check);
		if(num==check)
		goto game;
		else if(num!=check)
		{
			printf("Please check the code and enter it properly \n");
			goto check;
		}
		game:
		printf("\t\t\t\t\t---------------------------------------\n");
		printf("\t\t\t\t\t|         Welcome to Casino 9         |\n");
		printf("\t\t\t\t\t---------------------------------------\n");
		printf("Here we have 3 amazing number guessing games !!\nGO Ahead !!! Choose 1 of 3\n\n");
		printf("\t|%c|Enter 1 for Hi-Lo Game\n",4);
		printf("\t|%c|Enter 2 for Guess What ! game\n",4);
		printf("\t|%c|Enter 3 for In or Out !! game\n",4);
		printf("\t|%c|Enter 4 to Exit\n",4);
		scanf("%d",&z);
		if(z==1) 
		{
			system("cls");
			guess(N);
			goto game;
		}
    	else if(z==2) 
		{
			system("cls");
			guess2(N);
			goto game;
		}
    	else if (z==3) 
		{
			system("cls");
			guess3(N);
			goto game;
		}
    	else if (z==4) printf("Bye ! %c",2);
   		else printf("Enter either '1','2','3','4'");
    	return 0;
	}
}
